### ISSUE TITLE
Hi. I need help

### ISSUE THREAD

**Issue by F1xYou** [dazmaks/csharp-stealer#1]
**How to compile?**

**Comment by dazmaks** [comment]
You need to install [cmake ](https://cmake.org/download/)

**Comment by dazmaks** [comment]
1. You need to install [cmake](https://cmake.org/download/)

**Comment by dazmaks** [comment]
1. You need to install [cmake](https://cmake.org/download/)
2. Install .NET compiler for [windows](https://visualstudio.microsoft.com/) or [linux](https://www.mono-project.com/download/stable/)
3. `git clone https://github.com/dazmaks/csharp-stealer.git`
4. `cd csharp-stealer`
5. `make`
